//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessConnections
    {
        public int id { get; set; }
        public int businessId { get; set; }
        public int eventId { get; set; }
    }
}
